preferred_auth_method = "apikey"
model = "gpt-5.4"
model_reasoning_effort = "medium"
personality = "friendly"
suppress_unstable_features_warning = true

[features]
multi_agent = true
default_mode_request_user_input = true

[projects."/home/h-morishita/program/tanaoroshi"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

